### ISSUE TITLE
Update to Bootstrap 4.0 and other UI Terms

### ISSUE THREAD

**Issue by shantanoo-desai** [nimble-platform/frontend-service#39]
It might be worth update the Bootstrap 3.0 to 4.0. [4.0](http://getbootstrap.com/) is now a stable release.

Also It is worth mentioning that we use 

    <div class="container">

in the `index.html` and which gives it a column look and not using the complete spaces. Most of the websites start with `<div class="fluid-container">`. It might make the UI more appealing and also for our search component more beneficial as the graphical search requires a space which is limited due to the fixed container length.

However, this point is open for discussion.

**Comment by oliver-jung** [comment]
We are using the Angular version of Bootstrap (https://ng-bootstrap.github.io/) for proper TypeScript support of the framework (see package.json). ng-bootstrap already uses Bootstrap 4. We are still running a beta version that is a few months old (1.0.0-beta.5 for ng-bootstrap, 4.0.0-alpha.6 for the Bootstrap CSS) but I will upgrade to the stable release within the next weeks. There shouldn't be any major changes apart from cross-browser support bug fixes though.

The container class has been chosen on purpose. Actually it is not fixed in width but got specific max-width values depending on the viewport size. This ensures a tidy display especially on big screens / resolutions (e.g. stretching a simple input field on a full 4k display would look rather unpleasant and confusing).

In case a full width (container-fluid) is required / wanted for specific features we can nest a container (or max-width div) into a container-fluid in order to support both cases.

**Comment by shantanoo-desai** [comment]
Would [Material Angular](https://material.angular.io) be an interesting UI Library?

**Comment by oliver-jung** [comment]
Material is indeed a good and interesting framework but it is highly overlapping with Bootstrap features. From my point of view Material is mainly targeted at mobile devices and native apps while Bootstrap is more focused on the "browser world".
The current Bootstrap theme will be further improved, extended and unified in the course of the implementation of Release 3.
After that we can have a look at implementing some more "visually appealing" components and/or try introducing Material as an alternate "theme" for users to choose from in a separate branch.

**Comment by shantanoo-desai** [comment]
Hi @oliver-jung , Need to ask if there are some libraries within the repo that could handle Table filtering and sorting. If not what are the chances of using one for instance, [Ng2-tables](https://valor-software.com/ng2-table/) with MIT License.

The only drawback I see it that the particular library has its own `ngx-bootstrap` library and would might be undesirable perhaps.

**Comment by oliver-jung** [comment]
There are no specific libraries in place for this purpose.
Table filtering and sorting can be hand-crafted pretty easily. There is a filtering and sorting mechanism in place for the catalogue already that you can use as a reference (see src/app/catalogue/ubl-model-view/catalogue/catalogue-view.component).
If you prefer using a library ng2-tables looks good at first glance. Be sure to use the pagination mechanism of ng-bootstrap though in order to not mix things up.

**Comment by shantanoo-desai** [comment]
@oliver-jung Closing this issue since we anyways are on `Bootstrap 4.1.1`. Any further discussions regarding UI updated could be addressed in new issues.
